before:
  hooks:
    - go mod tidy
    - ./scripts/completions.sh
builds:
  - env:
      - CGO_ENABLED=0
    # GOOS list to build for.
    # For more info refer to: https://golang.org/doc/install/source#environment
    # Defaults are darwin and linux.
    goos:
      - linux
      - darwin
      - windows

    # GOARCH to build for.
    # For more info refer to: https://golang.org/doc/install/source#environment
    # Defaults are 386 and amd64.
    goarch:
      - amd64
      - arm
      - arm64

brews:
  - tap:
      owner: fhopfensperger
      name: homebrew-tap
    folder: Formula
    homepage: https://fhopfensperger.github.io
    description: Command line tool to create release branches and tags
    license: Apache 2.0
    test: |
      system "#{bin}/git-releaser -v"
    dependencies:
      - name: go
        type: optional
      - name: git
        type: optional
    install: |-
      bin.install "git-releaser"
      bash_completion.install "completions/git-releaser.bash" => "git-releaser"
      zsh_completion.install "completions/git-releaser.zsh" => "_git-releaser"
      fish_completion.install "completions/git-releaser.fish"
archives:
  - name_template: '{{ .ProjectName }}_{{ .Os }}_{{ .Arch }}{{ if .Arm }}v{{ .Arm }}{{ end }}'
    format_overrides:
      - goos: windows
        format: zip
    files:
      - README.md
      - LICENSE
      - completions/*